Repository secureCodeBox/secureCodeBox-v2, pull requests merged in 2020-08, with the labels that each got.

#70 Automatically Publish Helm Charts on Releases
  .github/workflows/helm-charts.yaml
  demo-apps/bodgeit/Chart.yaml
  demo-apps/juice-shop/Chart.yaml
Labels: ci

#64 Truncate overly long fields in ZAP Findings
  scanners/zap/parser/__snapshots__/parser.test.js.snap
  scanners/zap/parser/parser.js
Labels: bug

#67 Add Example Ressource Limits for Scanners
  scanners/amass/values.yaml
  scanners/nikto/values.yaml
  scanners/nmap/values.yaml
  scanners/ssh_scan/values.yaml
  scanners/sslyze/values.yaml
  scanners/test-scan/values.yaml
  scanners/trivy/values.yaml
  scanners/wpscan/values.yaml
  scanners/zap/values.yaml
Labels: documentation

#73 Feature/improve readme files
  hooks/declarative-subsequent-scans/README.md
  hooks/persistence-defectdojo/README.md
  hooks/persistence-elastic/README.md
  hooks/slack-webhook/README.md
  hooks/teams-webhook/README.md
  hooks/update-field/README.md
  scanners/amass/README.md
  scanners/kube-hunter/README.md
  scanners/kubeaudit/README.md
  scanners/ncrack/README.md
  scanners/nikto/README.md
  scanners/nmap/README.md
  scanners/ssh_scan/README.md
  scanners/sslyze/README.md
  scanners/trivy/README.md
  scanners/wpscan/README.md
  scanners/zap/README.md
Labels: documentation

#74 Bugfixing some typos
  hooks/persistence-defectdojo/README.md
Labels: documentation

#77 Update Readme to reflect the project maturity
  README.md
Labels: documentation

#76 Added the persistence Hook for static reporting
  docs/developer-guide/README.md
  docs/user-guide/README.md
  hooks/declarative-subsequent-scans/README.md
  hooks/generic-webhook/README.md
  hooks/imperative-subsequent-scans/README.md
  hooks/persistence-defectdojo/README.md
  hooks/persistence-elastic/README.md
  hooks/persistence-static-report/README.md
  hooks/slack-webhook/README.md
  hooks/teams-webhook/README.md
  hooks/update-field/README.md
  scanners/amass/README.md
  scanners/kube-hunter/README.md
  scanners/kubeaudit/README.md
  scanners/ncrack/README.md
  scanners/nikto/README.md
  scanners/nmap/README.md
  scanners/ssh_scan/README.md
  scanners/sslyze/README.md
  scanners/trivy/README.md
  scanners/wpscan/README.md
  scanners/zap/README.md
Labels: documentation

#79 Update supported Kubernetes version range to include v1.19
  .github/workflows/ci.yaml
  README.md
Labels: ci, dependencies
