Repository secureCodeBox/secureCodeBox-v2, pull requests merged in 2020-07, with the labels that each got.

#40 #30 ADR Hook Concept
  docs/adr/adr_0001.adoc
Labels: architecture, documentation

#49 Allow to Specify ENV Vars in the Scan CRD
  operator/apis/execution/v1/scan_types.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/cascading.experimental.securecodebox.io_cascadingrules.yaml
  operator/config/crd/bases/execution.experimental.securecodebox.io_scans.yaml
  operator/config/crd/bases/execution.experimental.securecodebox.io_scheduledscans.yaml
  operator/controllers/execution/scan_controller.go
  operator/crds/cascading.experimental.securecodebox.io_cascadingrules.yaml
  operator/crds/execution.experimental.securecodebox.io_scans.yaml
  operator/crds/execution.experimental.securecodebox.io_scheduledscans.yaml
Labels: enhancement

#32 Feature/read only hooks
  .github/workflows/ci.yaml
  demo-apps/http-webhook/.helmignore
  demo-apps/http-webhook/Chart.yaml
  demo-apps/http-webhook/templates/NOTES.txt
  demo-apps/http-webhook/templates/_helpers.tpl
  demo-apps/http-webhook/templates/deployment.yaml
  demo-apps/http-webhook/templates/hpa.yaml
  demo-apps/http-webhook/templates/ingress.yaml
  demo-apps/http-webhook/templates/service.yaml
  demo-apps/http-webhook/templates/serviceaccount.yaml
  demo-apps/http-webhook/templates/tests/test-connection.yaml
  demo-apps/http-webhook/values.yaml
  tests/integration/generic/read-only-hook.test.js
Labels: testing

#44 Prevent duplicated hooks
  operator/controllers/execution/scan_controller.go
Labels: bug

#58 Allow Hooks to use custom ServiceAccounts
  hooks/declarative-subsequent-scans/templates/declerative-subsequent-scans-hook.yaml
  hooks/declarative-subsequent-scans/templates/role-binding.yaml
  hooks/declarative-subsequent-scans/templates/role.yaml
  hooks/declarative-subsequent-scans/templates/service-account.yaml
  hooks/imperative-subsequent-scans/templates/imperative-subsequent-scans-hook.yaml
  hooks/imperative-subsequent-scans/templates/role-binding.yaml
  hooks/imperative-subsequent-scans/templates/role.yaml
  hooks/imperative-subsequent-scans/templates/service-account.yaml
  operator/apis/execution/v1/scancompletionhook.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/execution.experimental.securecodebox.io_scancompletionhooks.yaml
  operator/controllers/execution/scan_controller.go
  operator/crds/execution.experimental.securecodebox.io_scancompletionhooks.yaml
Labels: enhancement

#59 Add Example Nikto Scans
  bin/install-all.sh
  bin/uninstall-all.sh
  scanners/nikto/examples/demo-bodgeit/findings.yaml
  scanners/nikto/examples/demo-bodgeit/nikto-results.json
  scanners/nikto/examples/demo-bodgeit/scan.yaml
  scanners/nikto/examples/demo-juice-shop/findings.yaml
  scanners/nikto/examples/demo-juice-shop/nikto-results.json
  scanners/nikto/examples/demo-juice-shop/scan.yaml
  scanners/nikto/examples/demo-secureCodeBox.io/scan.yaml
Labels: documentation

#52 Providing Two New Architecture Diagrams
  docs/uml/_copyright.ipuml
  docs/uml/_iteratecTheme.ipuml
  docs/uml/compononents_overview.png
  docs/uml/compononents_overview.uxf
  docs/uml/sequence_overview.png
  docs/uml/sequence_overview.puml
Labels: architecture, documentation

#63 Fix Declarative CombinedScans Hooks from crashing when used by a ScheduledScan
  hooks/declarative-subsequent-scans/hook.test.js
  hooks/declarative-subsequent-scans/hook.ts
  hooks/declarative-subsequent-scans/scan-helpers.ts
Labels: bug
