Repository secureCodeBox/secureCodeBox-v2, pull requests merged in 2020-10, with the labels that each got.

#128 Add Cascading Rules for Ncrack
  .github/workflows/ci.yaml
  scanners/ncrack/cascading-rules/crackssh.yaml
  scanners/ncrack/templates/cascading-rules.yaml
  scanners/nmap/examples/dummy-ssh-cascade/scan.yaml
  tests/integration/helpers.js
  tests/integration/scanner/cascade.test.js
Labels: Hacktoberfest, enhancement, security scanner

#131 Fix Ncrack Group Name
  scanners/ncrack/cascading-rules/crackssh.yaml
  scanners/nmap/examples/dummy-ssh-cascade/scan.yaml
  tests/integration/helpers.js
Labels: bug, ci

#129 Add securityContexts to secureCodeBox Components
  hook-sdk/nodejs/Dockerfile
  lurcher/Dockerfile
  operator/Dockerfile
  operator/README.md
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/scan_reconciler.go
  operator/templates/manager/manager.yaml
  operator/values.yaml
  parser-sdk/nodejs/Dockerfile
  scanners/amass/Chart.yaml
  scanners/amass/README.md
  scanners/amass/README.md.gotmpl
  scanners/amass/helm2.Chart.yaml
  scanners/amass/templates/amass-scan-type.yaml
  scanners/amass/values.yaml
  scanners/kube-hunter/README.md
  scanners/kube-hunter/templates/kubehunter-scan-type.yaml
  scanners/kube-hunter/values.yaml
  scanners/ncrack/README.md
  scanners/ncrack/templates/ncrack-scan-type.yaml
  scanners/ncrack/values.yaml
  scanners/nikto/README.md
  scanners/nikto/templates/nikto-scan-type.yaml
  scanners/nikto/values.yaml
  scanners/nmap/README.md
  scanners/nmap/README.md.gotmpl
  scanners/nmap/scanner/Dockerfile
  scanners/nmap/templates/nmap-scan-type.yaml
  scanners/nmap/values.yaml
  scanners/ssh_scan/README.md
  scanners/ssh_scan/templates/ssh-scan-scan-type.yaml
  scanners/ssh_scan/values.yaml
  scanners/sslyze/README.md
  scanners/sslyze/templates/sslyze-scan-type.yaml
  scanners/sslyze/values.yaml
  scanners/test-scan/README.md
  scanners/test-scan/templates/test-scan-scan-type.yaml
  scanners/test-scan/values.yaml
  scanners/trivy/README.md
  scanners/trivy/templates/trivy-scan-type.yaml
  scanners/trivy/values.yaml
  scanners/wpscan/README.md
  scanners/wpscan/templates/wpscan-scan-type.yaml
  scanners/wpscan/values.yaml
  scanners/zap/README.md
  scanners/zap/templates/zap-scan-type.yaml
  scanners/zap/values.yaml
Labels: enhancement

#133 Update Minio to latest version
  operator/Chart.lock
  operator/Chart.yaml
  operator/charts/minio-5.0.19.tgz
  operator/charts/minio-7.1.2.tgz
Labels: enhancement

#140 Cleanup Unused / Badly named CRD Attributes
  operator/apis/execution/v1/parsedefinition_types.go
  operator/apis/execution/v1/scheduledscan_types.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/execution.securecodebox.io_parsedefinitions.yaml
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/config/samples/execution_v1_parsedefinition.yaml
  operator/config/samples/execution_v1_scheduledscan.yaml
  operator/controllers/execution/scheduledscan_controller.go
  operator/crds/execution.securecodebox.io_parsedefinitions.yaml
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
Labels: documentation, enhancement

#142 Add ADR Proposal for Documentation Versioning
  docs/adr/adr_0006.adoc
Labels: documentation
