Repository secureCodeBox/secureCodeBox-v2, pull requests merged in 2020-06, with the labels that each got.

#7 Improving the readme badges
  .codeclimate.yml
  .github/workflows/ci.yaml
  README.md
Labels: documentation

#26 Fix Crashes of Scans with long Names
  operator/Dockerfile
  operator/controllers/execution/scan_controller.go
  operator/utils/truncatedname.go
  operator/utils/truncatedname_test.go
  tests/integration/helpers.js
Labels: bug

#28 Improve developer guide
  .envrc
  .gitignore
  README.md
  bin/install-all.sh
  bin/uninstall-all.sh
  docs/developer-guide/README.md
Labels: documentation

#35 Added helm charts for some more demo/testing apps.
  README.md
  demo-apps/README.md
  demo-apps/bodgeit/.helmignore
  demo-apps/bodgeit/Chart.yaml
  demo-apps/bodgeit/questions.yml
  demo-apps/bodgeit/templates/NOTES.txt
  demo-apps/bodgeit/templates/_helpers.tpl
  demo-apps/bodgeit/templates/deployment.yaml
  demo-apps/bodgeit/templates/ingress.yaml
  demo-apps/bodgeit/templates/service.yaml
  demo-apps/bodgeit/templates/tests/test-connection.yaml
  demo-apps/bodgeit/values.yaml
  demo-apps/juice-shop/.helmignore
  demo-apps/juice-shop/Chart.yaml
  demo-apps/juice-shop/questions.yml
  demo-apps/juice-shop/templates/NOTES.txt
  demo-apps/juice-shop/templates/_helpers.tpl
  demo-apps/juice-shop/templates/deployment.yaml
  demo-apps/juice-shop/templates/ingress.yaml
  demo-apps/juice-shop/templates/service.yaml
  demo-apps/juice-shop/templates/tests/test-connection.yaml
  demo-apps/juice-shop/values.yaml
  demo-apps/old-wordpress/.helmignore
  demo-apps/old-wordpress/Chart.yaml
  demo-apps/old-wordpress/questions.yml
  demo-apps/old-wordpress/templates/NOTES.txt
  demo-apps/old-wordpress/templates/_helpers.tpl
  demo-apps/old-wordpress/templates/deployment.yaml
  demo-apps/old-wordpress/templates/service.yaml
  demo-apps/old-wordpress/templates/tests/test-connection.yaml
  demo-apps/old-wordpress/values.yaml
  demo-apps/swagger-petstore/.helmignore
  demo-apps/swagger-petstore/Chart.yaml
  demo-apps/swagger-petstore/questions.yml
  demo-apps/swagger-petstore/templates/NOTES.txt
  demo-apps/swagger-petstore/templates/_helpers.tpl
  demo-apps/swagger-petstore/templates/deployment.yaml
  demo-apps/swagger-petstore/templates/ingress.yaml
  demo-apps/swagger-petstore/templates/service.yaml
  demo-apps/swagger-petstore/templates/tests/test-connection.yaml
  demo-apps/swagger-petstore/values.yaml
Labels: testing

#43 #42 Add imagePullSecrets to ParseDefinition and ScanCompletionHooks
  operator/apis/execution/v1/parsedefinition_types.go
  operator/apis/execution/v1/scancompletionhook.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/execution.experimental.securecodebox.io_parsedefinitions.yaml
  operator/config/crd/bases/execution.experimental.securecodebox.io_scancompletionhooks.yaml
  operator/controllers/execution/scan_controller.go
  operator/crds/execution.experimental.securecodebox.io_parsedefinitions.yaml
  operator/crds/execution.experimental.securecodebox.io_scancompletionhooks.yaml
Labels: enhancement

#38 Add Resource Limits to Scans
  operator/controllers/execution/scan_controller.go
  scanners/amass/templates/amass-scan-type.yaml
  scanners/amass/values.yaml
  scanners/kube-hunter/templates/kubehunter-scan-type.yaml
  scanners/kube-hunter/values.yaml
  scanners/nikto/templates/nikto-scan-type.yaml
  scanners/nikto/values.yaml
  scanners/nmap/templates/nmap-scan-type.yaml
  scanners/nmap/values.yaml
  scanners/ssh_scan/templates/ssh-scan-scan-type.yaml
  scanners/ssh_scan/values.yaml
  scanners/sslyze/templates/sslyze-scan-type.yaml
  scanners/sslyze/values.yaml
  scanners/test-scan/templates/test-scan-scan-type.yaml
  scanners/test-scan/values.yaml
  scanners/trivy/templates/trivy-scan-type.yaml
  scanners/trivy/values.yaml
  scanners/wpscan/templates/wpscan-scan-type.yaml
  scanners/wpscan/values.yaml
  scanners/zap/templates/zap-scan-type.yaml
  scanners/zap/values.yaml
Labels: enhancement

#41 Update several Scanner Versions
  .github/workflows/ci.yaml
  scanners/amass/Chart.yaml
  scanners/amass/templates/amass-scan-type.yaml
  scanners/nmap/Chart.yaml
  scanners/nmap/scanner/Dockerfile
  scanners/sslyze/Chart.yaml
  scanners/sslyze/templates/sslyze-scan-type.yaml
Labels: enhancement
