Repository secureCodeBox/secureCodeBox-v2, pull requests merged in 2020-09, with the labels that each got.

#80 Send Anonymous Telemetry Data
  .github/workflows/ci.yaml
  operator/Dockerfile
  operator/internal/telemetry/telemetry.go
  operator/main.go
  operator/templates/NOTES.txt
  operator/templates/manager/manager.yaml
  operator/values.yaml
Labels: enhancement

#82 Add completion timestamp to scans once finished
  operator/apis/execution/v1/scan_types.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/execution.experimental.securecodebox.io_scans.yaml
  operator/controllers/execution/scans/hook_reconciler.go
  operator/crds/execution.experimental.securecodebox.io_scans.yaml
Labels: enhancement

#83 Add Presigned URLs to download Scan Results to Scan Status
  operator/PROJECT
  operator/apis/execution/v1/scan_types.go
  operator/config/crd/bases/execution.experimental.securecodebox.io_scans.yaml
  operator/config/crd/kustomization.yaml
  operator/config/rbac/host_editor_role.yaml
  operator/config/rbac/host_viewer_role.yaml
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/scan_controller.go
  operator/controllers/execution/scans/scan_reconciler.go
Labels: enhancement

#90 Added correct licence informations to the npm package files.
  hooks/declarative-subsequent-scans/package.json
  hooks/generic-webhook/package.json
  hooks/imperative-subsequent-scans/package.json
  hooks/package.json
  hooks/persistence-elastic/package.json
  hooks/update-field/package.json
  package.json
  scanners/package.json
Labels: bug

#91 Include actual namespace in error message
  operator/controllers/execution/scans/scan_reconciler.go
  tests/integration/generic/no-scan-definition-error.test.js
Labels: enhancement

#88 Add ncrack scanner implementation
  .github/workflows/ci.yaml
  scanners/ncrack/.helmignore
  scanners/ncrack/Chart.yaml
  scanners/ncrack/examples/dummy-ssh/README.md
  scanners/ncrack/examples/dummy-ssh/scan.yaml
  scanners/ncrack/parser/.dockerignore
  scanners/ncrack/parser/.gitignore
  scanners/ncrack/parser/Dockerfile
  scanners/ncrack/parser/__testFiles__/ncrack_no_results.xml
  scanners/ncrack/parser/__testFiles__/ncrack_two_services_no_results.xml
  scanners/ncrack/parser/__testFiles__/ncrack_two_services_with_results.xml
  scanners/ncrack/parser/__testFiles__/ncrack_with_results.xml
  scanners/ncrack/parser/package-lock.json
  scanners/ncrack/parser/package.json
  scanners/ncrack/parser/parser.js
  scanners/ncrack/parser/parser.test.js
  scanners/ncrack/scanner/Dockerfile
  scanners/ncrack/templates/ncrack-parse-definition.yaml
  scanners/ncrack/templates/ncrack-scan-type.yaml
  scanners/ncrack/values.yaml
  tests/integration/helpers.js
  tests/integration/scanner/ncrack.test.js
Labels: enhancement

#93 Ensure Helm Charts use corresponding Container Image Versions
  .github/workflows/ci.yaml
  demo-apps/bodgeit/Chart.yaml
  demo-apps/dummy-ssh/Chart.yaml
  demo-apps/http-webhook/Chart.yaml
  demo-apps/juice-shop/Chart.yaml
  demo-apps/old-wordpress/Chart.yaml
  demo-apps/swagger-petstore/Chart.yaml
  hooks/declarative-subsequent-scans/Chart.yaml
  hooks/declarative-subsequent-scans/templates/declerative-subsequent-scans-hook.yaml
  hooks/declarative-subsequent-scans/values.yaml
  hooks/generic-webhook/Chart.yaml
  hooks/generic-webhook/templates/webhook-hook.yaml
  hooks/generic-webhook/values.yaml
  hooks/imperative-subsequent-scans/Chart.yaml
  hooks/imperative-subsequent-scans/templates/imperative-subsequent-scans-hook.yaml
  hooks/imperative-subsequent-scans/values.yaml
  hooks/persistence-elastic/Chart.yaml
  hooks/persistence-elastic/templates/persistence-provider.yaml
  hooks/persistence-elastic/values.yaml
  hooks/update-field/Chart.yaml
  hooks/update-field/templates/update-field-hook.yaml
  hooks/update-field/values.yaml
  operator/Chart.yaml
  operator/templates/manager/manager.yaml
  operator/values.yaml
  scanners/amass/Chart.yaml
  scanners/amass/templates/amass-parse-definition.yaml
  scanners/amass/values.yaml
  scanners/kube-hunter/Chart.yaml
  scanners/kube-hunter/templates/kube-hunter-parse-definition.yaml
  scanners/kube-hunter/values.yaml
  scanners/ncrack/Chart.yaml
  scanners/ncrack/templates/ncrack-parse-definition.yaml
  scanners/ncrack/values.yaml
  scanners/nikto/Chart.yaml
  scanners/nikto/templates/nikto-parse-definition.yaml
  scanners/nikto/values.yaml
  scanners/nmap/Chart.yaml
  scanners/nmap/templates/nmap-parse-definition.yaml
  scanners/nmap/values.yaml
  scanners/ssh_scan/Chart.yaml
  scanners/ssh_scan/templates/ssh-scan-parse-definition.yaml
  scanners/ssh_scan/values.yaml
  scanners/sslyze/Chart.yaml
  scanners/sslyze/templates/sslyze-parse-definition.yaml
  scanners/sslyze/values.yaml
  scanners/test-scan/Chart.yaml
  scanners/test-scan/templates/test-scan-parse-definition.yaml
  scanners/test-scan/values.yaml
  scanners/trivy/Chart.yaml
  scanners/trivy/templates/trivy-parse-definition.yaml
  scanners/trivy/values.yaml
  scanners/wpscan/Chart.yaml
  scanners/wpscan/templates/wpscan-parse-definition.yaml
  scanners/wpscan/values.yaml
  scanners/zap/Chart.yaml
  scanners/zap/templates/zap-parse-definition.yaml
  scanners/zap/values.yaml
Labels: ci, enhancement

#97 Add Integration Tests for ZAP
  .github/workflows/ci.yaml
  scanners/amass/templates/amass-scan-type.yaml
  scanners/amass/values.yaml
  scanners/kube-hunter/templates/kubehunter-scan-type.yaml
  scanners/kube-hunter/values.yaml
  scanners/ncrack/templates/ncrack-scan-type.yaml
  scanners/ncrack/values.yaml
  scanners/nikto/templates/nikto-scan-type.yaml
  scanners/nikto/values.yaml
  scanners/nmap/templates/nmap-scan-type.yaml
  scanners/nmap/values.yaml
  scanners/ssh_scan/templates/ssh-scan-scan-type.yaml
  scanners/ssh_scan/values.yaml
  scanners/sslyze/templates/sslyze-scan-type.yaml
  scanners/sslyze/values.yaml
  scanners/test-scan/templates/test-scan-scan-type.yaml
  scanners/test-scan/values.yaml
  scanners/trivy/templates/trivy-scan-type.yaml
  scanners/trivy/values.yaml
  scanners/wpscan/templates/wpscan-scan-type.yaml
  scanners/wpscan/values.yaml
  scanners/zap/templates/zap-scan-type.yaml
  tests/integration/helpers.js
  tests/integration/scanner/zap.test.js
Labels: testing

#111 Adding new Badges
  README.md
Labels: documentation

#61 Contributing
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#112 Allow to Change Attribute Names on the S3 Secret
  operator/templates/manager/manager.yaml
  operator/values.yaml
Labels: enhancement

#115 Fixing CodeClimate Integration
  .github/workflows/ci.yaml
Labels: bug

#113 Trying to support helm2 in parallel to helm3 (WIP).
  .github/workflows/helm-charts.yaml
  hooks/declarative-subsequent-scans/helm2.Chart.yaml
  hooks/generic-webhook/helm2.Chart.yaml
  hooks/imperative-subsequent-scans/helm2.Chart.yaml
  hooks/persistence-elastic/helm2.Chart.yaml
  hooks/persistence-elastic/helm2.requirements.lock
  hooks/persistence-elastic/helm2.requirements.yaml
  hooks/update-field/helm2.Chart.yaml
  operator/helm2.Chart.yaml
  operator/helm2.requirements.lock
  operator/helm2.requirements.yaml
  scanners/amass/helm2.Chart.yaml
  scanners/kube-hunter/helm2.Chart.yaml
  scanners/ncrack/helm2.Chart.yaml
  scanners/nikto/helm2.Chart.yaml
  scanners/nmap/helm2.Chart.yaml
  scanners/ssh_scan/helm2.Chart.yaml
  scanners/sslyze/helm2.Chart.yaml
  scanners/test-scan/helm2.Chart.yaml
  scanners/trivy/helm2.Chart.yaml
  scanners/wpscan/helm2.Chart.yaml
  scanners/zap/helm2.Chart.yaml
Labels: enhancement

#117 Disable Istio Injection for Scan/Parser/Hook Pods
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/scan_reconciler.go
Labels: bug

#121 Added Helm2 Chart version additional to helm3 for all demo apps.
  demo-apps/bodgeit/helm2.Chart.yaml
  demo-apps/dummy-ssh/helm2.Chart.yaml
  demo-apps/juice-shop/helm2.Chart.yaml
  demo-apps/old-wordpress/helm2.Chart.yaml
  demo-apps/swagger-petstore/helm2.Chart.yaml
Labels: ci
